name: Run python code daily

on:
    workflow_dispatch:

    schedule:
        - cron: '0 0 1 * *'

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: 3.8


            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run python script
              run: python main.py

            - name: Upload Excel file
              uses: actions/upload-artifact@v3
              with:
                name: tag_along_excel  # Nome do artefato
                path: tag_along.xlsx   # Caminho para o arquivo gerado





